admissionController:
  tufRoot: "$(TUF_MIRROR)/root.json"
  tufMirror: "$(TUF_MIRROR)"
  customSigstoreConfigMap: tufvalues

reportsController:
  tufRoot: "$(TUF_MIRROR)/root.json"
  tufMirror: "$(TUF_MIRROR)"
  customSigstoreConfigMap: tufvalues
