admissionController:
  tufRoot: "./root.json"
  tufMirror: "$(TUF_MIRROR)"
  customSigstoreConfigMap: tufvalues

reportsController:
  tufRoot: "./root.json"
  tufMirror: "$(TUF_MIRROR)"
  customSigstoreConfigMap: tufvalues